version: '3.9'
services:
  db:
    image: postgres:16.4
    container_name: pettz-db
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_ROOT_HOST: '%'
      POSTGRES_TCP_PORT: 5433
    ports:
      - "5433:5433"
    expose:
      - 5433
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - pettz-network
  pettz:
    image: edielsonassis/pettz
    container_name: pettz-api
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/${DATABASE_NAME}?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ${DATABASE_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${DATABASE_PASSWORD}
      ALLOWED_MAPPINGS: ${ALLOWED_MAPPINGS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ALLOWED_METHODS: ${ALLOWED_METHODS}
      ALLOWED_HEADERS: ${ALLOWED_HEADERS}
      MAX_AGE: ${MAX_AGE}
      SECRET_KEY: ${SECRET_KEY}
      EXPIRATION_TOKEN: ${EXPIRATION_TOKEN}
      EXPIRATION_REFRESH_TOKEN: ${EXPIRATION_REFRESH_TOKEN}
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - pettz-network
networks:
  pettz-network:
    driver: bridge
volumes:
  postgres-data: