# Server settings
server:
  port: 80
  error:
    include-stacktrace: never

# CORS settings
cors:
  allowedMappings: ${ALLOWED_MAPPINGS}
  allowedOrigins: ${ALLOWED_ORIGINS}
  allowedMethods: ${ALLOWED_METHODS}
  allowedHeaders: ${ALLOWED_HEADERS}
  maxAge: ${MAX_AGE}

# Security JWT settings
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expiration-length: ${EXPIRATION_TOKEN}
      refresh-expiration-length: ${EXPIRATION_REFRESH_TOKEN}

# Spring datasource settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

# Connection pool configurations
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: "SELECT 1"
      maximum-pool-size: 20
      minimum-idle: 10
      initialization-fail-timeout: 2000
      isolate-internal-queries: true
      validation-timeout: 3000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

# Spring JPA settings
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

# File settings
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 10MB

file:
  upload-dir: ${PRODUCT_IMAGE}

# SpringDoc settings
springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    use-root-path: true